$.lang.register('chatmoderator.usage.toggles', 'Uso: !moderation [links / caps / symbols / spam / emotes / colors / longmessages / spamtracker / regulars / subscribers / silenttimeout]');
$.lang.register('chatmoderator.usage.messages', 'Uso: !moderation [linksmessage / capsmessage / symbolsmessage / spammessage / emotesmessage / colorsmessage / blacklistmessage / longmsgmessage / spamtrackermessage]');
$.lang.register('chatmoderator.options', 'Uso: !moderation [capstriggerlength / capslimit / symbolstriggerlength / symbolslimit / symbolsgrouplimit / spamlimit / emoteslimit / spamtrackerlimit / spamtrackertime / permittime / warningtime / timeouttime / messagecooldown / messagecharacterlimit / blacklisttimeouttime / warningresettime]');
$.lang.register('chatmoderator.link.usage', 'Uso: !moderation links [on / off] (el filtro de links está $1)');
$.lang.register('chatmoderator.link.filter.enabled', 'filtro de links habilitado.');
$.lang.register('chatmoderator.msgcooldown.usage', 'Uso: !moderation messagecooldown [tiempo en segundos]');
$.lang.register('chatmoderator.msgcooldown.set', 'cooldown de mensajes establecido en $1 segundos.');
$.lang.register('chatmoderator.warningresettime.usage', 'Uso: !moderation warningresettime [tiempo en minutos]');
$.lang.register('chatmoderator.warningresettime.set', 'tiempo de reseteo de alertas establecido en $1 minuto.');
$.lang.register('chatmoderator.link.filter.disabled', 'filtro de links deshabilitado.');
$.lang.register('chatmoderator.message.limit.usage', 'Uso: !moderation messagecharacterlimit [cantidad]');
$.lang.register('chatmoderator.message.limit.set', 'máximo de caracteres permitidos en un mensaje establecido en $1 caracteres.');
$.lang.register('chatmoderator.message.message.usage', 'Uso: !moderation longmsgmessage [mensaje]');
$.lang.register('chatmoderator.message.message.set', 'mensaje de mensajes largos establecido en $1');
$.lang.register('chatmoderator.message.usage', 'Uso: !moderation longmessages [on / off] (el filtro de mensajes largos está $1)');
$.lang.register('chatmoderator.message.filter.enabled', 'filtro de mensajes largos habilitado.');
$.lang.register('chatmoderator.message.filter.disabled', 'filtro de mensajes largos deshabilitado.');
$.lang.register('chatmoderator.caps.usage', 'Uso: !moderation caps [on / off] (filtro de mayúsculas está $1)');
$.lang.register('chatmoderator.caps.filter.enabled', 'filtro de mayúsculas habilitado.');
$.lang.register('chatmoderator.caps.filter.disabled', 'filtro de mayúsculas deshabilitado.');
$.lang.register('chatmoderator.spam.usage', 'Uso: !moderation spam [on / off] (filtro de spam está $1)');
$.lang.register('chatmoderator.spam.filter.enabled', 'filtro de spam habilitado.');
$.lang.register('chatmoderator.spam.filter.disabled', 'filtro de spam deshabilitado.');
$.lang.register('chatmoderator.spamtracker.usage', 'Uso: !moderation spamtracker [on / off] (filtro de seguimiento de spam está $1)');
$.lang.register('chatmoderator.spamtracker.filter.enabled', 'filtro de seguimiento de spam habilitado.');
$.lang.register('chatmoderator.spamtracker.filter.disabled', 'filtro de seguimiento de spam deshabilitado.');
$.lang.register('chatmoderator.symbols.usage', 'Uso: !moderation symbols [on / off] (filtro de símbolos está $1)');
$.lang.register('chatmoderator.symbols.filter.enabled', 'filtro de símbolos habilitado.');
$.lang.register('chatmoderator.symbols.filter.disabled', 'filtro de símbolos deshabilitado.');
$.lang.register('chatmoderator.emotes.usage', 'Uso: !moderation emotes [on / off] (filtro de emotes está $1)');
$.lang.register('chatmoderator.emotes.filter.enabled', 'filtro de emotes habilitado.');
$.lang.register('chatmoderator.emotes.filter.disabled', 'filtro de emotes deshabilitado.');
$.lang.register('chatmoderator.colors.usage', 'Uso: !moderation colors [on / off] (filtro de colores está $1)');
$.lang.register('chatmoderator.colors.filter.enabled', 'filtro de colores habilitado.');
$.lang.register('chatmoderator.colors.filter.disabled', 'filtro de colores deshabilitado.');
$.lang.register('chatmoderator.regulars.usage', 'Uso: !moderation regulars [links / caps / symbols / spam / emotes / colors / longmessages / spamtracker] [true / false]');
$.lang.register('chatmoderator.subscribers.usage', 'Uso: !moderation subscribers [links / caps / symbols / spam / emotes / colors / longmessages / spamtracker] [true / false]');
$.lang.register('chatmoderator.subscribers.links.allowed', 'los subscriptores ahora estarán afectados por el filtro de links.');
$.lang.register('chatmoderator.subscribers.links.not.allowed', 'los subscrptores ya no estarán afectados por el filtro de links.');
$.lang.register('chatmoderator.subscribers.caps.allowed', 'los subscriptores ahora estarán afectados por el filtro de mayúsculas.');
$.lang.register('chatmoderator.subscribers.caps.not.allowed', 'los subscriptores ya no estarán afectados por el filtro de mayúsculas.');
$.lang.register('chatmoderator.subscribers.symbols.allowed', 'los subscriptores ahora estarán afectados por el filtro de símbolos.');
$.lang.register('chatmoderator.subscribers.symbols.not.allowed', 'los subscriptores ya no estarán afectados por el filtro de símbolos.');
$.lang.register('chatmoderator.subscribers.spam.allowed', 'los subscriptores ahora estarán afectados por el filtro de spam.');
$.lang.register('chatmoderator.subscribers.spam.not.allowed', 'los subscriptores ya no estarán afectados por el filtro de spam.');
$.lang.register('chatmoderator.subscribers.emotes.allowed', 'los subscriptores ahora estarán afectados por el filtro de emotes.');
$.lang.register('chatmoderator.subscribers.emotes.not.allowed', 'los subscriptores ya no estarán afectados por el filtro de emotes.');
$.lang.register('chatmoderator.subscribers.spamtracker.allowed', 'los subscriptores ahora estarán afectados por el filtro de seguimiento de spam.');
$.lang.register('chatmoderator.subscribers.spamtracker.not.allowed', 'los subscriptores ya no estarán afectados por el filtro de seguimiento de spam.');
$.lang.register('chatmoderator.subscribers.colors.allowed', 'los subscriptores ahora estarán afectados por el filtro de colores.');
$.lang.register('chatmoderator.subscribers.colors.not.allowed', 'los subscriptores ya no estarán afectados por el filtro de colores.');
$.lang.register('chatmoderator.subscribers.long.messages.allowed', 'los subscriptores ahora estarán afectados por el filtro de mensajes largos filter.');
$.lang.register('chatmoderator.subscribers.long.messages.not.allowed', 'los subscriptores ya no estarán afectados por el filtro de mensajes largos.');
$.lang.register('chatmoderator.subscribers.toggle.link', 'subscribers are currently $1 to post links.');
$.lang.register('chatmoderator.subscribers.toggle.caps', 'subscribers are currently $1 to type all in caps.');
$.lang.register('chatmoderator.subscribers.toggle.symbols', 'subscribers are currently $1 to spam symbols.');
$.lang.register('chatmoderator.subscribers.toggle.spam', 'subscribers are currently $1 to spam repeating characters.');
$.lang.register('chatmoderator.subscribers.toggle.emotes', 'subscribers are currently $1 to overuse emotes.');
$.lang.register('chatmoderator.subscribers.toggle.colors', 'subscribers are currently $1 to use /me for colored text');
$.lang.register('chatmoderator.subscribers.toggle.long.msg', 'subscribers are currently $1 to post long messages.');
$.lang.register('chatmoderator.regulars.links.allowed', 'regulars will now be effected by the link filter.');
$.lang.register('chatmoderator.regulars.links.not.allowed', 'regulars will no longer be effected by the link filter.');
$.lang.register('chatmoderator.regulars.caps.allowed', 'regulars will now be effected by the caps filter.');
$.lang.register('chatmoderator.regulars.caps.not.allowed', 'regulars will no longer be effected by the caps filter.');
$.lang.register('chatmoderator.regulars.symbols.allowed', 'regulars will now be effected by the symbols filter.');
$.lang.register('chatmoderator.regulars.symbols.not.allowed', 'regulars will no longer be effected by the symbols filter.');
$.lang.register('chatmoderator.regulars.spam.allowed', 'regulars will now be effected by the spam filter.');
$.lang.register('chatmoderator.regulars.spam.not.allowed', 'regulars will no longer be effected by the spam filter.');
$.lang.register('chatmoderator.regulars.emotes.allowed', 'regulars will now be effected by the emotes filter.');
$.lang.register('chatmoderator.regulars.emotes.not.allowed', 'regulars will no longer be effected by the emotes filter.');
$.lang.register('chatmoderator.regulars.spamtracker.allowed', 'regulars will now be effected by the spam tracker filter.');
$.lang.register('chatmoderator.regulars.spamtracker.not.allowed', 'regulars will no longer be effected by the spam tracker filter.');
$.lang.register('chatmoderator.regulars.colors.allowed', 'regulars will now be effected by the colors filter.');
$.lang.register('chatmoderator.regulars.colors.not.allowed', 'regulars will no longer be effected by the colors filter.');
$.lang.register('chatmoderator.regulars.long.messages.allowed', 'regulars will now be effected by the long message filter.');
$.lang.register('chatmoderator.regulars.long.messages.not.allowed', 'regulars will no longer be effected by the long message filter.');
$.lang.register('chatmoderator.regulars.toggle.link', 'regulars are currently $1 to post links.');
$.lang.register('chatmoderator.regulars.toggle.caps', 'regulars are currently $1 to type all in caps.');
$.lang.register('chatmoderator.regulars.toggle.symbols', 'regulars are currently $1 to spam symbols.');
$.lang.register('chatmoderator.regulars.toggle.spam', 'regulars are currently $1 to spam repeating characters.');
$.lang.register('chatmoderator.regulars.toggle.emotes', 'regulars are currently $1 to overuse emotes.');
$.lang.register('chatmoderator.regulars.toggle.colors', 'regulars are currently $1 to use /me for colored text');
$.lang.register('chatmoderator.regulars.toggle.long.msg', 'regulars are currently $1 to post long messages.');
$.lang.register('chatmoderator.silenttimeout.toggle.links', 'silent timeout is currently $1 for links.');
$.lang.register('chatmoderator.silenttimeout.usage.all', 'Uso: !moderation silenttimeout all [true / false]');
$.lang.register('chatmoderator.silenttimeout.true', 'silent timeout has been enabled for all filters.');
$.lang.register('chatmoderator.silenttimeout.false', 'silent timeout has been disabled for all filters.');
$.lang.register('chatmoderator.silenttimeout.toggle.caps', 'silent timeout is currently $1 for caps.');
$.lang.register('chatmoderator.silenttimeout.toggle.spamtracker', 'silent timeout is currently $1 for spam tracker.');
$.lang.register('chatmoderator.silenttimeout.toggle.symbols', 'silent timeout is currently $1 for symbols.');
$.lang.register('chatmoderator.silenttimeout.toggle.spam', 'silent timeout is currently $1 for spam.');
$.lang.register('chatmoderator.silenttimeout.toggle.emotes', 'silent timeout is currently $1 for emotes.');
$.lang.register('chatmoderator.silenttimeout.toggle.colors', 'silent timeout is currently $1 for colors.');
$.lang.register('chatmoderator.silenttimeout.toggle.long.message', 'silent timeout is currently $1 for long messages.');
$.lang.register('chatmoderator.silenttimeout.toggle.blacklist', 'silent timeout is currently $1 for blacklist.');
$.lang.register('chatmoderator.silenttimeout.links.true', 'silent timeout has been turned on for links.');
$.lang.register('chatmoderator.silenttimeout.caps.true', 'silent timeout has been turned on for caps.');
$.lang.register('chatmoderator.silenttimeout.symbols.true', 'silent timeout has been turned on for symbols.');
$.lang.register('chatmoderator.silenttimeout.spam.true', 'silent timeout has been turned on for spam.');
$.lang.register('chatmoderator.silenttimeout.spamtracker.true', 'silent timeout has been turned on for spam tracker.');
$.lang.register('chatmoderator.silenttimeout.emotes.true', 'silent timeout has been turned on for emotes.');
$.lang.register('chatmoderator.silenttimeout.colors.true', 'silent timeout has been turned on for colors.');
$.lang.register('chatmoderator.silenttimeout.long.msg.true', 'silent timeout has been turned on for long messages.');
$.lang.register('chatmoderator.silenttimeout.links.false', 'silent timeout has been turned off for links.');
$.lang.register('chatmoderator.silenttimeout.caps.false', 'silent timeout has been turned off for caps.');
$.lang.register('chatmoderator.silenttimeout.symbols.false', 'silent timeout has been turned off for symbols.');
$.lang.register('chatmoderator.silenttimeout.spam.false', 'silent timeout has been turned off for spam.');
$.lang.register('chatmoderator.silenttimeout.spamtracker.false', 'silent timeout has been turned off for spam tracker.');
$.lang.register('chatmoderator.silenttimeout.emotes.false', 'silent timeout has been turned off for emotes.');
$.lang.register('chatmoderator.silenttimeout.colors.false', 'silent timeout has been turned off for colors.');
$.lang.register('chatmoderator.silenttimeout.long.msg.false', 'silent timeout has been turned off for long messages.');
$.lang.register('chatmoderator.silenttimeout.blacklist.messages.false', 'silent timeout has been turned off for blacklist.');
$.lang.register('chatmoderator.silenttimeout.blacklist.messages.true', 'silent timeout has been turned on for blacklist.');
$.lang.register('chatmoderator.silenttimeout.usage', 'Uso: !moderation silenttimeout [links / caps / symbols / spam / emotes / colors / longmessages / blacklist / spamtracker / all] [true / false]');
$.lang.register('chatmoderator.link.message.usage', 'Uso: !moderation linksmessage [message]');
$.lang.register('chatmoderator.link.message.set', 'link warning message set to: $1');
$.lang.register('chatmoderator.caps.message.usage', 'Uso: !moderation capsmessage [message]');
$.lang.register('chatmoderator.caps.message.set', 'cap warning message set to: $1');
$.lang.register('chatmoderator.symbols.message.usage', 'Uso: !moderation symbolsmessage [message]');
$.lang.register('chatmoderator.symbols.message.set', 'symbol warning message set to: $1');
$.lang.register('chatmoderator.emotes.message.usage', 'Uso: !moderation emotesmessage [message]');
$.lang.register('chatmoderator.emotes.message.set', 'emotes warning message set to: $1');
$.lang.register('chatmoderator.spam.message.usage', 'Uso: !moderation spammessage [message]');
$.lang.register('chatmoderator.spam.message.set', 'spam warning message set to: $1');
$.lang.register('chatmoderator.spamtracker.message.usage', 'Uso: !moderation spamtrackermessage [message]');
$.lang.register('chatmoderator.spamtracker.message.set', 'spam tracker warning message set to: $1');
$.lang.register('chatmoderator.colors.message.usage', 'Uso: !moderation colorsmessage [message]');
$.lang.register('chatmoderator.colors.message.set', 'color warning message set to: $1');
$.lang.register('chatmoderator.blacklist.message.usage', 'Uso: !moderation blacklistmessage [message]');
$.lang.register('chatmoderator.blacklist.message.set', 'blacklist warning message set to: $1');
$.lang.register('chatmoderator.permit.time.usage', 'Uso: !moderation permittime [time]');
$.lang.register('chatmoderator.permit.time.set', 'link permit time set to: $1 seconds.');
$.lang.register('chatmoderator.caps.limit.usage', 'Uso: !moderation capslimit [amount in percent]');
$.lang.register('chatmoderator.caps.limit.set', 'cap limit set to: $1% of caps.');
$.lang.register('chatmoderator.caps.trigger.length.set', 'cap trigger length set to: $1');
$.lang.register('chatmoderator.caps.trigger.length.usage', 'Uso: !moderation capstriggerlength [amount]');
$.lang.register('chatmoderator.spam.limit.usage', 'Uso: !moderation spamlimit [amount]');
$.lang.register('chatmoderator.spam.limit.set', 'spam limit set to: $1');
$.lang.register('chatmoderator.spamtracker.limit.usage', 'Uso: !moderation spamtrackerlimit [amount]');
$.lang.register('chatmoderator.spamtracker.limit.set', 'spam tracker limit set to: $1 message');
$.lang.register('chatmoderator.spamtracker.time.usage', 'Uso: !moderation spamtrackertime [amount in seconds]');
$.lang.register('chatmoderator.spamtracker.time.set', 'spam tracker time set to: $1 seconds');
$.lang.register('chatmoderator.symbols.limit.usage', 'Uso: !moderation symbolslimit [amount]');
$.lang.register('chatmoderator.symbols.limit.set', 'symbol limit set to: $1% of symbols');
$.lang.register('chatmoderator.symbols.group.limit.usage', 'Uso: !moderation symbolsgrouplimit [amount]');
$.lang.register('chatmoderator.symbols.group.limit.set', 'grouped symbol limit set to: $1 symbols');
$.lang.register('chatmoderator.symbols.trigger.length.usage', 'Uso: !moderation symbolsTriggerLength [amount]');
$.lang.register('chatmoderator.symbols.trigger.length.set', 'symbol trigger length set to: $1');
$.lang.register('chatmoderator.emotes.limit.usage', 'Uso: !moderation emoteslimit [amount]');
$.lang.register('chatmoderator.emotes.limit.set', 'emotes limit set to: $1 emotes');
$.lang.register('chatmoderator.permit.usage', 'Uso: !permit [username]');
$.lang.register('chatmoderator.permited', ' is now permitted to post one link during the next $1 seconds!');
$.lang.register('chatmoderator.blacklist.usage', 'Uso: !blackList [add / remove / show]');
$.lang.register('chatmoderator.blacklist.add.usage', 'Uso: !blackList add (message)');
$.lang.register('chatmoderator.blacklist.added', 'Word added to the blacklist.');
$.lang.register('chatmoderator.blacklist.remove.usage', 'Uso: !blackList remove (id)');
$.lang.register('chatmoderator.err', 'That\'s an invalid id.');
$.lang.register('chatmoderator.blacklist.removed', 'Word removed from the blacklist.');
$.lang.register('chatmoderator.blacklist.show.usage', 'Uso: !blackList show (id)');
$.lang.register('chatmoderator.whitelist.usage', 'Uso: !whiteList [add / remove / show]');
$.lang.register('chatmoderator.whitelist.add.usage', 'Uso: !whiteList add (url)');
$.lang.register('chatmoderator.whitelist.link.added', 'Link added to the whiteList.');
$.lang.register('chatmoderator.whitelist.remove.usage', 'Uso: !whiteList remove (id)');
$.lang.register('chatmoderator.whitelist.removed', 'Link removed from the whitelist!');
$.lang.register('chatmoderator.whitelist.show.usage', 'Uso: !whiteList show (id)');
$.lang.register('chatmoderator.warning', '(warning)');
$.lang.register('chatmoderator.timeout', '(timeout)');
$.lang.register('chatmoderator.blacklisttimeouttime.set', 'blacklist timeout time set to $1 seconds.');
$.lang.register('chatmoderator.blacklisttimeouttime.usage', '!moderation blacklisttimeouttime [tiempo en segundos] (blacklist timeout time is currently $1 seconds)');
$.lang.register('chatmoderator.warningtime.usage', '!moderation warningtime [links / caps / symbols / spam / emotes / colors / longmessages / spamtracker] [tiempo en segundos]');
$.lang.register('chatmoderator.warningtime.links.usage', '!moderation warning time links [tiempo en segundos] (current warning time for links is set to $1 seconds)');
$.lang.register('chatmoderator.warningtime.links', 'warning time for links has been set to $1 seconds.');
$.lang.register('chatmoderator.warningtime.caps.usage', '!moderation warning time caps [tiempo en segundos] (current warning time for caps is set to $1 seconds)');
$.lang.register('chatmoderator.warningtime.caps', 'warning time for caps has been set to $1 seconds.');
$.lang.register('chatmoderator.warningtime.symbols.usage', '!moderation warning time symbols [tiempo en segundos] (current warning time for symbols is set to $1 seconds)');
$.lang.register('chatmoderator.warningtime.symbols', 'warning time for symbols has been set to $1 seconds.');
$.lang.register('chatmoderator.warningtime.spam.usage', '!moderation warning time spam [tiempo en segundos] (current warning time for spam is set to $1 seconds)');
$.lang.register('chatmoderator.warningtime.spam', 'warning time for spam has been set to $1 seconds.');
$.lang.register('chatmoderator.warningtime.spamtracker.usage', '!moderation warning time spamtracker [tiempo en segundos] (current warning time for spam tracker is set to $1 seconds)');
$.lang.register('chatmoderator.warningtime.spamtracker', 'warning time for spam tracker has been set to $1 seconds.');
$.lang.register('chatmoderator.warningtime.colors.usage', '!moderation warning time colors [tiempo en segundos] (current warning time for colors is set to $1 seconds)');
$.lang.register('chatmoderator.warningtime.colors', 'warning time for colors has been set to $1 seconds.');
$.lang.register('chatmoderator.warningtime.emotes.usage', '!moderation warning time emotes [tiempo en segundos] (current warning time for emotes is set to $1 seconds)');
$.lang.register('chatmoderator.warningtime.emotes', 'warning time for emotes has been set to $1 seconds.');
$.lang.register('chatmoderator.warningtime.longmsg.usage', '!moderation warning time longmessages [tiempo en segundos] (current warning time for long messages is set to $1 seconds)');
$.lang.register('chatmoderator.warningtime.longmsg', 'warning time for long messages has been set to $1 seconds.');
$.lang.register('chatmoderator.timeouttime.usage', '!moderation timeouttime [links / caps / symbols / spam / emotes / colors / longmessages / spamtracker] [tiempo en segundos]');
$.lang.register('chatmoderator.timeouttime.links.usage', '!moderation timeout time links [tiempo en segundos] (current timeout time for links is set to $1 seconds)');
$.lang.register('chatmoderator.timeouttime.links', 'timeout time for links has been set to $1 seconds.');
$.lang.register('chatmoderator.timeouttime.caps.usage', '!moderation timeout time caps [tiempo en segundos] (current timeout time for caps is set to $1 seconds)');
$.lang.register('chatmoderator.timeouttime.caps', 'timeout time for caps has been set to $1 seconds.');
$.lang.register('chatmoderator.timeouttime.symbols.usage', '!moderation timeout time symbols [tiempo en segundos] (current timeout time for symbols is set to $1 seconds)');
$.lang.register('chatmoderator.timeouttime.symbols', 'timeout time for symbols has been set to $1 seconds.');
$.lang.register('chatmoderator.timeouttime.spam.usage', '!moderation timeout time spam [tiempo en segundos] (current timeout time for spam is set to $1 seconds)');
$.lang.register('chatmoderator.timeouttime.spam', 'timeout time for spam has been set to $1 seconds.');
$.lang.register('chatmoderator.timeouttime.spamtracker.usage', '!moderation timeout time spamtracker [tiempo en segundos] (current timeout time for spam tracker is set to $1 seconds)');
$.lang.register('chatmoderator.timeouttime.spamtracker', 'timeout time for spam tracker has been set to $1 seconds.');
$.lang.register('chatmoderator.timeouttime.colors.usage', '!moderation timeout time colors [tiempo en segundos] (current timeout time for colors is set to $1 seconds)');
$.lang.register('chatmoderator.timeouttime.colors', 'timeout time for colors has been set to $1 seconds.');
$.lang.register('chatmoderator.timeouttime.emotes.usage', '!moderation timeout time emotes [tiempo en segundos] (current timeout time for emotes is set to $1 seconds)');
$.lang.register('chatmoderator.timeouttime.emotes', 'timeout time for emotes has been set to $1 seconds.');
$.lang.register('chatmoderator.timeouttime.longmsg.usage', '!moderation timeout time longmessages [tiempo en segundos] (current timeout time for long messages is set to $1 seconds)');
$.lang.register('chatmoderator.timeouttime.longmsg', 'timeout time for long messages has been set to $1 seconds.');
$.lang.register('chatmoderator.timeouttime.err', 'your timeout time for the spam tracker can not be lower then your spam tracker time.');
$.lang.register('chatmoderator.warningtime.err', 'your warning time for the spam tracker can not be lower then your spam tracker time.');
$.lang.register('cmd.404', 'el comando !$1 no existe o no está registrado.');
$.lang.register('cmd.adminonly', 'Only an Administrator has access to that command!');
$.lang.register('cmd.casteronly', 'Only a Caster has access to that command!');
$.lang.register('cmd.modonly', 'Only a Moderator has access to that command!');
$.lang.register('cmd.needpoints', 'El comando cuesta $1, no tienes suficientes.');
$.lang.register('cmd.perm.404', 'solamente un $1 o superior tiene acceso a ese comando.');
$.lang.register('commandlist.commands', 'Comandos (página $1 de $2): $3');
$.lang.register('commandlist.more', ' >> Escribe "!commands $1" para ver más');
$.lang.register('commandlist.nocommands', 'Actualmente no hay comandos dispoibles para ti');
$.lang.register('commandlist.nopage', 'la página $1 no existe!');
$.lang.register('commandlist.progress', 'Exportando comandos... $1%');
$.lang.register('commandpause.ended', 'All commands are enabled again.');
$.lang.register('commandpause.initiated', 'All commands are disabled for $1.');
$.lang.register('commandpause.isactive', 'All commands are currently disabled.');
$.lang.register('common.disabled', 'deshabilitado');
$.lang.register('common.enabled', 'habilitado');
$.lang.register('common.user-error', 'You must specify a user to target with this command');
$.lang.register('common.user.404', 'El usuario "$1" aún no ha visitado este canal.');
$.lang.register('console.channel.ishosting', '$1 ahora está hosteando a $2.');
$.lang.register('console.received.clearchat', 'Received a clear chat notification from jtv');
$.lang.register('console.received.host.end', 'Received an end host mode notification from jtv');
$.lang.register('console.received.host.start', 'Received a start host mode notification on user $1 from jtv');
$.lang.register('console.received.irsprivmsg', 'Recibido un whisper de $1: $2');
$.lang.register('console.received.purgetimeoutban', 'Received a purge/timeout/ban notification on user $1 from jtv');
$.lang.register('console.received.r9k.end', 'Received an end r9k mode notification from jtv');
$.lang.register('console.received.r9k.start', 'Received a start r9k mode notification from jtv');
$.lang.register('console.received.slowmode.end', 'Received an end slow mode notification from jtv');
$.lang.register('console.received.slowmode.start', 'Received a start slow mode ($1) notification from jtv');
$.lang.register('console.received.subscriberonly.end', 'Received an end subscribers-only mode notification from jtv');
$.lang.register('console.received.subscriberonly.start', 'Received a start subscribers-only mode notification from jtv');
$.lang.register('cooldown.set.togglemodcooldown', 'Command cooldowns have been $1 for moderators.');
$.lang.register('cooldown.set.usage', 'Uso: !cooldown [command] [tiempo en segundos]');
$.lang.register('cooldown.global.usage', 'Uso: !globalcooldowntime [tiempo en segundos]');
$.lang.register('cooldown.global.toggle', 'global cooldown has been $1.');
$.lang.register('cooldown.per.user.toggle', 'per-user cooldown has been $1.');
$.lang.register('cooldown.global.set', 'global cooldown set to $1 seconds.');
$.lang.register('cooldown.removed', 'cooldown for command !$1 has been removed.');
$.lang.register('cooldown.set', 'cooldown for command !$1 has been set to $2 seconds.');
$.lang.register('init.cmsgset', 'Connected message set!');
$.lang.register('init.module.404', 'That module does not exist or is not loaded!');
$.lang.register('init.module.check.disabled', 'Módulo $1 está desactivado!');
$.lang.register('init.module.check.enabled', 'Módulo $1 está activado!');
$.lang.register('init.module.auto-disabled', 'Modules related to pointSystem have been disabled. See logs.');
$.lang.register('init.module.disabled', 'Módulo "$1" deshabilitado!');
$.lang.register('init.module.enabled', 'Módulo "$1" habilitado!');
$.lang.register('init.module.error', 'Módulo "$1" habilitado pero no se ha inicializado! Revisa los logs de errores!');
$.lang.register('init.module.list', 'Módulos (* están deshabilitados): $1');
$.lang.register('init.module.list.total', 'Total Pages: $1');
$.lang.register('init.module.usage', 'Uso: !module list, !module enable [module name], !module disable [module name], !module status [module name]');
$.lang.register('init.reconnect', 'Reconnecting to $1');
$.lang.register('init.rejoin', 'Rejoining the channel.');
$.lang.register('init.disconnect', 'Disconnecting from $1');
$.lang.register('init.usage', '!$1 [reconnect / disconnect / connectmessage / removeconnectmessage / blacklist]');
$.lang.register('init.connected.msg', 'Connect message set to: $1');
$.lang.register('init.connected.msg.Uso', '!$1 connectmessage [message]');
$.lang.register('init.connected.msg.removed', 'Connect message removed!');
$.lang.register('init.blacklist.usage', 'Uso: !$1 blacklist [add / remove]');
$.lang.register('init.blacklist.add.usage', 'Uso: !$1 blacklist add (username)');
$.lang.register('init.blacklist.added', 'added $1 to the bot blacklist!');
$.lang.register('init.blacklist.remove.usage', 'Uso: !$1 blacklist remove (username)');
$.lang.register('init.blacklist.err', 'that user is not in the blacklist.');
$.lang.register('init.blacklist.removed', 'removed $1 from the bot blacklist!');
$.lang.register('init.mod.toggle.on.pay', 'moderators+ will now pay for commands.');
$.lang.register('init.mod.toggle.off.pay', 'moderators+ will no longer pay for commands.');
$.lang.register('init.mod.toggle.perm.msg.off', 'No permission messages have been disabled.');
$.lang.register('init.toggle.cooldown.msg.on', 'The cooldown message has been enabled.');
$.lang.register('init.toggle.cooldown.msg.off', 'The cooldown message has been disabled.');
$.lang.register('init.cooldown.msg', 'command !$1 is still on cooldown. ($2 seconds)');
$.lang.register('lang.curlang', 'The current language is $1!');
$.lang.register('lang.lang.404', 'That language file does not exist!');
$.lang.register('lang.lang.changed', 'Changed language to $1!');
$.lang.register('lang.response.action.disabled', 'Chat output will be normal text. (without /me)');
$.lang.register('lang.response.action.enabled', 'Chat output wil be prepended with "/me".');
$.lang.register('lang.response.disabled', 'Responses are now disabled! To enable them, use !mute');
$.lang.register('lang.response.enabled', 'Responses are now enabled! To disable them, use: !mute');
$.lang.register('logging.enabled.files', 'File and chat logging has been enabled!');
$.lang.register('logging.disabled.files', 'File and chat logging has been disabled!');
$.lang.register('logging.enabled.event', 'Event logging has been enabled!');
$.lang.register('logging.disabled.event', 'Event logging has been disabled!');
$.lang.register('logging.enabled.error', 'Error logging has been enabled!');
$.lang.register('logging.disabled.error', 'Error logging has been disabled!');
$.lang.register('logging.usage', 'Uso: !log [files / errors / events]');
$.lang.register('logging.rotatedays.usage', 'Uso: !log rotatedays [days]. 0 to keep all logs. Currently: $1');
$.lang.register('logging.rotatedays.success', 'Logs will rotate every $1 days.');
$.lang.register('logging.rotatedays.success.off', 'Logs will not be rotated');
$.lang.register('permissions.current.listtoolong', 'There are over $1 to list, I suggest checking the viewerslist in the Twitch chat.');
$.lang.register('permissions.current.mods', 'Mods in channel: $1');
$.lang.register('permissions.current.users', 'Users in channel: $1');
$.lang.register('permissions.group.self.current', 'You currently have $1 permissions.');
$.lang.register('permissions.group.other.current', '$1 currently has $2 permissions.');
$.lang.register('permissions.group.set.error.abovegroup', 'You must have higher permissions than the person you are trying to promote!');
$.lang.register('permissions.group.set.error.samegroup', 'You cannot promote others to the same permission as you.');
$.lang.register('permissions.group.set.success', 'Permission for $1 changed to $2!');
$.lang.register('permissions.group.usage', 'Uso: !permission, !permission [name] [permissionID]');
$.lang.register('permissions.grouppoints.usage', 'Uso: !permissionpoints [group] [online|offline] [points]. points of -1 uses !setgain, !setofflinegain values.');
$.lang.register('permissions.grouppoints.showgroup', 'Permission $1 gains $2 $3 online and $4 $5 offline.');
$.lang.register('permissions.grouppoints.showgroup.online', '$1 gains $2 $3 online.');
$.lang.register('permissions.grouppoints.showgroup.offline', '$1 gains $2 $3 offline.');
$.lang.register('permissions.grouppoints.set.online', 'Set permission $1 to gain $2 $3 online.');
$.lang.register('permissions.grouppoints.set.offline', 'Set permission $1 to gain $2 $3 offline.');
$.lang.register('permissions.grouppoints.set.sub.error', 'You cannot promote anyone to Subscriber, this status is from Twitch is GameWisp.');
$.lang.register('timesystem.uptime.offline', '$1 is currently offline.');
$.lang.register('timesystem.uptime', '$1 has been live for $2!');
$.lang.register('timesystem.add.error.negative', 'You can not give negative time.');
$.lang.register('timesystem.add.success', 'Sent $1 to $2. New balance is $3.');
$.lang.register('timesystem.add.usage', 'Uso: "!time give [name] [amount]"');
$.lang.register('timesystem.autolevel.disabled', 'Users will no longer be promoted to $1 when they have been in the chat for $2 hour(s).');
$.lang.register('timesystem.autolevel.enabled', 'Users will now be promoted to $1 when they have been in the chat for $2 hour(s).');
$.lang.register('timesystem.autolevel.promoted', '$1 has been promoted to $2 by being in the chat for $3 hour(s). Congratulations!');
$.lang.register('timesystem.get.other', '$1 currently spent $2 in the chat.');
$.lang.register('timesystem.get.self', 'you currently have spent $2 in the chat.');
$.lang.register('timesystem.modpermtoggle.success', 'Users in the group $1 or higher are now able to use time management commands.');
$.lang.register('timesystem.offlinetime.disabled', 'Offline time will not longer be counted towards the time.');
$.lang.register('timesystem.offlinetime.enabled', 'Offline time will now be counted towards the time.');
$.lang.register('timesystem.set.promotehours.error.negative', 'You can not set the time in hours to promote a user to $1 to a negative number.');
$.lang.register('timesystem.set.promotehours.success', 'Set the time in hours to promote a user to $1 to $2.');
$.lang.register('timesystem.set.promotehours.usage', 'Uso: "!time promotehours [amount]"');
$.lang.register('timesystem.set.timezone.invalid', '"$1" is not a valid time zone. A list of time zones can be found on "http://en.wikipedia.org/wiki/List_of_tz_database_time_zones".');
$.lang.register('timesystem.set.timezone.success', 'The time zone has been set to "$1". Automatically adjusts for daylight saving time: $2');
$.lang.register('timesystem.set.timezone.usage', 'Uso: !timezone [timezone name] (Current timezone is $1)');
$.lang.register('timesystem.settime.error.negative', 'You can not set a balance to negative time.');
$.lang.register('timesystem.settime.success', 'Set the time balance of $1 to $2.');
$.lang.register('timesystem.settime.usage', 'Uso: "!time set [name] [amount]"');
$.lang.register('timesystem.streamertime', 'It is currently $1 where $2 is located.');
$.lang.register('timesystem.take.error.toomuch', 'You can not take more than what $1 has in time.');
$.lang.register('timesystem.take.success', 'Taken $1 from $2. New balance is $3.');
$.lang.register('timesystem.take.usage', 'Uso: "!time take [name] [amount]"');
$.lang.register('get.long.time.string.short', ' $1 days, $2 hours and $3 minutes.');
$.lang.register('get.long.time.string.long', '$1 months, $2 hours and $3 minutes.');
$.lang.register('user.time.string.hours', ' $1 hours and $2 minutes');
$.lang.register('user.time.string.minutes', ' $1 minutes');
$.lang.register('whisper.whispers.disabled', '[Whisper Mode] has been disabled.');
$.lang.register('whisper.whispers.enabled', '[Whisper Mode] has been enabled.');
$.lang.register('pausecommands.usage', 'Uso: !pausecommands [seconds | clear]');
$.lang.register('common.hours', ' horas, ');
$.lang.register('common.hours2', ' horas, ');
$.lang.register('common.hours3', ' horas');
$.lang.register('common.minutes', ' minutos y ');
$.lang.register('common.minutes2', ' minutos.');
$.lang.register('common.seconds', ' segundos');
$.lang.register('common.get.age.days', '$1 $2 lleva en Twitch desde $3. (Se unió hace $4 días)');
$.lang.register('common.get.age', '$1 $2 lleva en Twitch desde $3.');
$.lang.register('channel.age.user.404', 'El usuario no está en Twitch.');
